import type { CharacterProfile, ProductionForm, ResolvedObjectPath, ResolvedProductionConcept, ResolvedSpatialActionPlan } from "./production-types";

export type FinalizedProductionBeat = { id: string; startSeconds: number; endSeconds: number; label: string; visualAction: string };
export type TimedDirectionBeat = { startSeconds: number; endSeconds: number; direction: string };
export type PromptFinalizationIssue = { id: string; title: string; severity: "critical" | "major" | "minor"; evidence: string; affectedSection: string; recommendedRepair: string; repairable: boolean };
export type CharacterFinalState = { characterId: string; characterName: string; finalZoneId: string; finalPosture: string; finalFacing: string; finalExpression: string; supported: boolean; visible: boolean; settled: boolean };
export type ObjectFinalState = { objectId: string; objectName: string; finalZoneId: string; finalPositionDescription: string; finalOrientation: string; supported: boolean; visible: boolean; settled: boolean };
export type PhysicalRedirectionPlan = { actorName: string; bodyPart: "foot" | "tail" | "hand" | "paw" | "shoulder" | "authorized-object"; objectName: string; contactPoint: string; preparation: string; contactAction: string; momentumResponse: string; newDirection: string; resultingPath: string };
export type ObjectMotionProfile = { objectName: string; shape: "round" | "cylindrical" | "flat" | "irregular" | "flexible" | "box-like" | "unknown"; supportedMovementTypes: ("roll" | "wobble" | "slide" | "bounce" | "swing" | "fall" | "carry" | "launch")[]; preferredMotionDescription: string };
export type ResolvedLocationPlan = { locationName: string; environmentType: "indoor" | "outdoor" | "mixed"; primaryArea: string; actionSurface: string; nearbyStructure?: string; lighting: string; allowedVocabulary: string[]; forbiddenVocabulary: string[] };
export type AuthorizedObjectDescriptor = { id: string; name: string; aliases: string[]; attributes: string[] };

const problem = (id: string, title: string, evidence: string, affectedSection: string, recommendedRepair: string, severity: PromptFinalizationIssue["severity"] = "major"): PromptFinalizationIssue => ({ id, title, severity, evidence, affectedSection, recommendedRepair, repairable: true });
const time = (seconds: number) => `0:${String(seconds).padStart(2, "0")}`;

export function getFinalizedProductionBeats(production: { resolvedSpatialActionPlan: ResolvedSpatialActionPlan; concept: ResolvedProductionConcept }): FinalizedProductionBeat[] {
  const labels = ["Hook and trap launch", "Dodge and interference", "Backfire", "Payoff"];
  return production.resolvedSpatialActionPlan.beats.map((beat, index) => ({ id: `finalized-${index}`, startSeconds: beat.startSeconds, endSeconds: beat.endSeconds, label: labels[index] || `Beat ${index + 1}`, visualAction: "" }));
}

export function buildMusicFromFinalizedBeats({ beats, form }: { beats: FinalizedProductionBeat[]; concept: ResolvedProductionConcept; form: ProductionForm }): TimedDirectionBeat[] {
  if (form.noMusic || form.musicStyle === "no-music") return [];
  return beats.map((beat, index) => ({ startSeconds: beat.startSeconds, endSeconds: beat.endSeconds, direction: index === 0 ? "Introduce a quick playful pulse under the trap launch." : index === 1 ? "Raise tension through the block and physical redirection." : index === 2 ? "Place one soft comedic accent exactly on the visible collision." : "Resolve with a cheerful cadence as every character and the important object settle." }));
}

export function buildSfxFromFinalizedBeats({ beats, concept }: { beats: FinalizedProductionBeat[]; concept: ResolvedProductionConcept; characterVocalLocks: string[]; form: ProductionForm }): TimedDirectionBeat[] {
  return beats.map((beat, index) => ({ startSeconds: beat.startSeconds, endSeconds: beat.endSeconds, direction: index === 0 ? `one effort reaction, ${concept.primaryObject.objectName} surface contact, and accelerating movement` : index === 1 ? `one quick step, one selected contact sound, and a sharp directional swish` : index === 2 ? `return movement, startled reactions, and one soft synchronized collision` : `${concept.primaryObject.objectName} wobble or scrape, friction slowdown, character settling, and one finishing reaction` }));
}

export function repairAudioTiming({ videoBeats, musicBeats, sfxBeats }: { videoBeats: FinalizedProductionBeat[]; musicBeats: TimedDirectionBeat[]; sfxBeats: TimedDirectionBeat[] }) {
  const align = (source: TimedDirectionBeat[]) => videoBeats.map((beat, index) => ({ startSeconds: beat.startSeconds, endSeconds: beat.endSeconds, direction: source[index]?.direction || "Follow the visible action in this beat." }));
  return { musicBeats: align(musicBeats), sfxBeats: align(sfxBeats), repaired: videoBeats.some((beat, index) => musicBeats[index]?.startSeconds !== beat.startSeconds || musicBeats[index]?.endSeconds !== beat.endSeconds || sfxBeats[index]?.startSeconds !== beat.startSeconds || sfxBeats[index]?.endSeconds !== beat.endSeconds) };
}
export function renderTimedDirections(beats: TimedDirectionBeat[]): string { return beats.map((beat) => `${time(beat.startSeconds)}–${time(beat.endSeconds)} — ${beat.direction}`).join("\n"); }

export function validateAllCharacterFinalStates({ selectedCharacters, finalStates, payoffText }: { selectedCharacters: CharacterProfile[]; finalStates: CharacterFinalState[]; payoffText: string }): PromptFinalizationIssue[] {
  return selectedCharacters.flatMap((character) => { const state = finalStates.find((entry) => entry.characterId === character.id); if (!state) return [problem("missing-character-final-state", "Missing character final state", `${character.shortName} has no structured final state.`, "Video Prompt — Payoff", `Name ${character.shortName}'s final zone, posture, expression, visibility, support, and settled state.`, "critical")]; const missing = !state.finalZoneId || !state.finalPosture || !state.finalFacing || !state.finalExpression || !state.supported || !state.visible || !state.settled || !new RegExp(`\\b${character.shortName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i").test(payoffText); return missing ? [problem("missing-character-final-state", "Incomplete character final state", `${character.shortName} is not explicitly and completely settled in the payoff.`, "Video Prompt — Payoff", `Write ${character.shortName}'s reachable final position and settled pose explicitly.`, "critical")] : []; });
}

export function validateObjectFinalState({ objectPath, finalState, videoLock, payoffText }: { objectPath: ResolvedObjectPath; finalState?: ObjectFinalState; videoLock: string; payoffText: string }): PromptFinalizationIssue[] {
  if (!finalState) return [problem("missing-object-final-state", "Missing object final state", `${objectPath.objectName} has no structured final state.`, "Video Prompt — Payoff", "Add visible slowdown, exact final position, orientation, support, visibility, and settling.", "critical")];
  const issues: PromptFinalizationIssue[] = [];
  if (!new RegExp(`\\b${objectPath.objectName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i").test(payoffText)) issues.push(problem("final-state-only-in-video-lock", "Object final state only appears in Video Lock", videoLock.match(new RegExp(`.{0,60}${objectPath.objectName}.{0,80}`, "i"))?.[0] || objectPath.objectName, "Video Prompt — Payoff", `State ${objectPath.objectName}'s final visible movement and position in the payoff.`, "critical"));
  if (finalState.finalZoneId !== objectPath.finalZoneId || !finalState.finalPositionDescription || !finalState.finalOrientation || !finalState.supported || !finalState.visible || !finalState.settled || !/stop|settle|slow|wobbl|rest/i.test(payoffText)) issues.push(problem("missing-object-final-state", "Incomplete object final state", `${objectPath.objectName} does not visibly slow, stop, orient, and settle at ${objectPath.finalZoneId}.`, "Video Prompt — Payoff", "Complete the object's last movement, stop mechanism, exact position, and orientation.", "critical"));
  return issues;
}

export function choosePhysicalContactMethod({ character, object }: { character: CharacterProfile; object: AuthorizedObjectDescriptor; movementType: string; pacing: string; modelCapabilities: string[] }): PhysicalRedirectionPlan["bodyPart"] { const text = `${character.fullIdentity} ${character.description} ${character.movementStyle}`.toLowerCase(); if (/tail/.test(text)) return "tail"; if (/paw/.test(text)) return "paw"; if (/hand|human|monkey|ape/.test(text)) return "hand"; void object; return "foot"; }
export function renderPhysicalRedirection(plan: PhysicalRedirectionPlan): string { const article = plan.bodyPart === "foot" ? "one planted foot" : plan.bodyPart === "tail" ? "one visible tail tap" : plan.bodyPart === "authorized-object" ? "the selected object" : `one ${plan.bodyPart}`; return `${plan.actorName} ${plan.preparation}, uses ${article} to ${plan.contactAction} the ${plan.objectName}'s ${plan.contactPoint}, ${plan.momentumResponse}, and sends it ${plan.newDirection} along ${plan.resultingPath}.`; }
export function validateRenderedPhysicalAction(text: string): PromptFinalizationIssue[] { const malformed = /\b(?:foot|tail|paw|hand|pushes|taps|sidesteps|jumps)\s+or\s+(?:foot|tail|paw|hand|pushes|taps|sidesteps|jumps)\b|visible\s+lower\s+side\s+with|\{\{|\[\[|\bundefined\b/i.exec(text); return malformed ? [problem("malformed-physical-action", "Malformed physical action", malformed[0], "Video Prompt", "Choose one contact method and render one complete grammatical action sentence.", "major")] : []; }

export function inferObjectMotionProfile(object: AuthorizedObjectDescriptor): ObjectMotionProfile { const text = `${object.name} ${object.aliases.join(" ")} ${object.attributes.join(" ")}`.toLowerCase(); if (/ball|sphere|round|spiral|shell|seashell/.test(text)) return { objectName: object.name, shape: /shell|seashell/.test(text) ? "irregular" : "round", supportedMovementTypes: ["roll", "wobble", "slide", "bounce"], preferredMotionDescription: "rolls with a visible wobble, then slows through surface friction" }; if (/basket|box|crate|case/.test(text)) return { objectName: object.name, shape: "box-like", supportedMovementTypes: ["slide", "fall", "carry"], preferredMotionDescription: "slides or tumbles on an edge, then settles flat" }; if (/tile|card|sheet|plate/.test(text)) return { objectName: object.name, shape: "flat", supportedMovementTypes: ["slide", "fall"], preferredMotionDescription: "slides, may flip once, and settles flat" }; return { objectName: object.name, shape: "unknown", supportedMovementTypes: ["slide", "fall", "carry", "launch"], preferredMotionDescription: "moves with visible weight and surface contact" }; }
export function validateObjectMotionCompatibility({ objectProfile, trajectory }: { objectProfile: ObjectMotionProfile; trajectory: ResolvedObjectPath }): PromptFinalizationIssue[] { const used = trajectory.segments.map((segment) => segment.movementType === "redirect" || segment.movementType === "slow" || segment.movementType === "stop" ? null : segment.movementType).filter(Boolean); const incompatible = used.find((movement) => !objectProfile.supportedMovementTypes.includes(movement as never)); return incompatible ? [problem("object-motion-incompatible", "Object motion conflicts with shape", `${objectProfile.objectName} is ${objectProfile.shape} but is told to ${incompatible}.`, "Video Prompt", `Use motion such as: ${objectProfile.preferredMotionDescription}.`)] : []; }

export function resolveLocationPlan(concept: ResolvedProductionConcept): ResolvedLocationPlan { const text = `${concept.location.name} ${concept.location.visualDescription}`.toLowerCase(); const workshop = /workshop/.test(text); const outdoor = /forest|seaside|boardwalk|path|slope|outdoor/.test(text); return { locationName: concept.location.name, environmentType: workshop && outdoor ? "mixed" : outdoor ? "outdoor" : "indoor", primaryArea: workshop ? `outside ${concept.location.name}` : concept.location.name, actionSurface: /boardwalk/.test(text) ? "short sloped boardwalk path" : "short sloped stone path", nearbyStructure: workshop ? "workshop entrance" : undefined, lighting: /night|moon/.test(text) ? "clear night lighting" : "warm daylight", allowedVocabulary: [concept.location.name, "path", "route", "upper area", "lower area"], forbiddenVocabulary: [] }; }
export function validateLocationCoherence(location: ResolvedLocationPlan): PromptFinalizationIssue[] { return location.environmentType === "indoor" && /slope|path/.test(location.actionSurface) ? [problem("location-coherence", "Location relationship is unclear", `${location.locationName} is described as indoor while the action uses ${location.actionSurface}.`, "Start Frame", `Preserve ${location.locationName} and place the action outside or beside it.`)] : []; }
export function renderCoherentLocation(location: ResolvedLocationPlan): string { return `${location.environmentType === "mixed" ? "an outdoor area beside" : "at"} ${location.locationName}, on a ${location.actionSurface}${location.nearbyStructure ? ` near the ${location.nearbyStructure}` : ""}, in ${location.lighting}`; }
