"use client";

import Link from "next/link";
import { useState } from "react";
import { PublicFooter, PublicHeader } from "./public-site";
import styles from "./public-pages.module.css";
import compact from "./marketing-compact.module.css";
import { VideoTypeCards } from "./video-type-cards";
import { VideoStyleId } from "./video-styles";

type Card = { title: string; copy: string; detail?: string; href?: string };

function Layout({ eyebrow, title, intro, children, action = "Start Creating", actionHref = "/create" }: { eyebrow: string; title: string; intro: string; children: React.ReactNode; action?: string; actionHref?: string }) {
  return <main className={styles.shell}><PublicHeader /><section className={styles.hero}><p className={styles.eyebrow}>{eyebrow}</p><h1>{title}</h1><p className={styles.intro}>{intro}</p><Link className={styles.button} href={actionHref}>{action}</Link></section>{children}<PublicFooter /></main>;
}
function CardGrid({ cards }: { cards: Card[] }) { return <div className={styles.grid}>{cards.map((card) => <article className={styles.card} key={card.title}><h3>{card.title}</h3><p>{card.copy}</p>{card.detail && <small>Suitable for: {card.detail}</small>}{card.href && <Link href={card.href}>Create This Style →</Link>}</article>)}</div>; }

const videoTypeCreateHref: Record<VideoStyleId, string> = { slapstick: "/create?type=slapstick", cinematic: "/create?type=cinematic", anime: "/create?type=anime", "live-action": "/create?type=live-action", "cgi-fantasy": "/create?type=fantasy", "family-3d": "/create?type=family-animation", "stylized-3d": "/create?type=stylized-3d" };
export function VideoTypesSignaturePage() { return <main className={`marketing-shell ${compact.videoTypesPage}`}><PublicHeader /><section className={compact.videoTypesHero}><p className="eyebrow">DEDICATED WORKFLOWS</p><h1>Explore Video Types</h1><p className="hero-copy">Choose the visual style that fits your idea, then build a complete production pack designed for that format.</p></section><section className={`marketing-section ${compact.styleSection}`}><p className="section-copy">Each style uses the same clear, compact card language from the homepage—then opens the existing creation workflow with a matching starting direction.</p><VideoTypeCards hrefFor={(id) => videoTypeCreateHref[id]} appearance="signature" /></section><section className={compact.videoTypesCta}><div><p className="eyebrow">CONNECTED CREATION</p><h2>Ready to Build Your Production Pack?</h2><p>Choose a video type and begin creating structured prompts for your next production.</p></div><Link className="marketing-button" href="/create">Start Creating</Link></section><PublicFooter /></main>; }
export function CharacterBuilderPage() { const cards = ["Character Identity", "Visual Appearance", "Personality", "Role", "Clothing and Accessories", "Voice and Vocal Lock", "Movement Style", "Character Consistency", "Hero, Enemy, and Companion roles", "Saving characters to the library"].map((title) => ({ title, copy: `Define ${title.toLowerCase()} once, then carry that detail into selected production outputs.` })); return <Layout eyebrow="CHARACTER-FIRST CREATION" title="Build characters that remain recognizable from frame to frame" intro="Create an original identity with visual locks, behavior, role, movement, and sound guidance. Saved profiles remain available for future productions." action="Build a Character" actionHref="/character-builder/create"><section className={styles.section}><h2>A complete character profile</h2><CardGrid cards={cards} /></section><section className={styles.section}><article className={`${styles.card} ${styles.featured}`}><h3>Example: Biscuit</h3><p>A warm orange squirrel hero with a cream muzzle, a clear silhouette, expressive reactions, and an identity lock that keeps colors, proportions, and role consistent.</p><small>Example only—edit every detail to make your own character.</small></article></section></Layout>; }
export function PricingPage() { const [annual, setAnnual] = useState(false); const plans = [["Starter", "For exploring a repeatable creative workflow."], ["Creator", "For individuals shaping multiple video concepts."], ["Studio", "For teams coordinating a shared production process."], ["Business", "For organizations planning broader creative operations."]]; return <Layout eyebrow="PRICING" title="Plans structured for future commercial release" intro="Plan configuration, pricing, and included usage are not finalized in this preview. These cards provide a clear future-ready structure without inventing commercial terms."><section className={styles.section}><div className={styles.pricingToggle}><button className={!annual ? styles.selected : ""} onClick={() => setAnnual(false)}>Monthly</button><button className={annual ? styles.selected : ""} onClick={() => setAnnual(true)}>Annual</button></div><div className={styles.grid}>{plans.map(([name, copy]) => <article className={`${styles.card} ${name === "Creator" ? styles.featured : ""}`} key={name}><h3>{name}</h3><p>{copy}</p><small>{annual ? "Annual plan values: configurable before release." : "Monthly price: configurable before release."}</small><small>Production pack and credit allocation: configurable.</small><Link href={`/sign-in?plan=${name.toLowerCase()}`}>Choose {name}</Link></article>)}</div></section><section className={styles.section}><h2>Compare plan areas</h2><table className={styles.table}><thead><tr><th>Area</th><th>Starter</th><th>Creator</th><th>Studio</th><th>Business</th></tr></thead><tbody><tr><td>Production workflow</td><td>Configurable</td><td>Configurable</td><td>Configurable</td><td>Configurable</td></tr><tr><td>Team controls</td><td>—</td><td>Configurable</td><td>Configurable</td><td>Configurable</td></tr></tbody></table><h2 style={{ marginTop: 42 }}>Questions about future plans</h2><p className={styles.notice}>Credits, billing, and final plan limits are not connected in this preview. No hidden-fee or usage claims are made here.</p></section></Layout>; }
export function SignInPage() { const [show, setShow] = useState(false); return <Layout eyebrow="ACCOUNT ACCESS" title="Sign in to continue your creative workflow" intro="Account authentication is not connected in this preview. This screen is intentionally a structured interface only and does not submit or store credentials." action="Open the Studio" actionHref="/create"><section className={styles.section}><form className={styles.form} onSubmit={(event) => event.preventDefault()}><label>Email<input type="email" autoComplete="email" placeholder="you@example.com" /></label><label>Password<input type={show ? "text" : "password"} autoComplete="current-password" placeholder="••••••••" /></label><div className={styles.formRow}><label><input type="checkbox" /> Remember me</label><a href="#account-help">Forgot password?</a></div><div className={styles.formRow}><button type="button" onClick={() => setShow((value) => !value)}>{show ? "Hide password" : "Show password"}</button><button type="submit">Sign In</button></div><p id="account-help" className={styles.notice}>Authentication is not yet connected. Create-account and recovery actions are not operational in this preview.</p></form></section></Layout>; }
