"use client";

import Link from "next/link";
import { useState } from "react";
import { PublicFooter, PublicHeader } from "./public-site";
import styles from "./public-pages.module.css";
import compact from "./marketing-compact.module.css";
import { VideoTypeCards } from "./video-type-cards";
import { VideoStyleId } from "./video-styles";

type Card = { title: string; copy: string; detail?: string; href?: string };
const productionCards: Card[] = [
  "Complete Video Idea|A connected premise with location, object, action, and payoff.", "Video Title|An editable, distinctive episode name.", "Start Frame Prompt|A clear first reference image and opening hook.", "End Frame Prompt|A stable payoff frame aligned with the opening.", "Main Video Prompt|One synchronized production prompt with video lock and timeline.", "Second-by-Second Timeline|Readable action beats across the selected duration.", "Camera and Motion Instructions|A controlled camera plan and physical motion guidance.", "Music Direction|Mood and timing that support the action.", "Sound Effects|Timed physical and nonverbal audio cues.", "Voice or Vocal Layers|Optional narration and character vocal-lock guidance.", "Negative Prompt|Constraints that reduce unwanted visual changes.", "Character Consistency Instructions|Identity, wardrobe, scale, and role preservation.", "Model-Specific Instructions|Adapter guidance for the selected generator.", "Exportable Final Pack|Copy, save, and Word-ready production output.",
].map((value) => { const [title, copy] = value.split("|"); return { title, copy }; });

function Layout({ eyebrow, title, intro, children, action = "Start Creating", actionHref = "/create" }: { eyebrow: string; title: string; intro: string; children: React.ReactNode; action?: string; actionHref?: string }) {
  return <main className={styles.shell}><PublicHeader /><section className={styles.hero}><p className={styles.eyebrow}>{eyebrow}</p><h1>{title}</h1><p className={styles.intro}>{intro}</p><Link className={styles.button} href={actionHref}>{action}</Link></section>{children}<PublicFooter /></main>;
}
function CardGrid({ cards }: { cards: Card[] }) { return <div className={styles.grid}>{cards.map((card) => <article className={styles.card} key={card.title}><h3>{card.title}</h3><p>{card.copy}</p>{card.detail && <small>Suitable for: {card.detail}</small>}{card.href && <Link href={card.href}>Create This Style →</Link>}</article>)}</div>; }

const videoTypeCreateHref: Record<VideoStyleId, string> = { slapstick: "/create?type=slapstick", cinematic: "/create?type=cinematic", anime: "/create?type=anime", "live-action": "/create?type=live-action", "cgi-fantasy": "/create?type=fantasy", "family-3d": "/create?type=family-animation", "stylized-3d": "/create?type=stylized-3d" };
export function VideoTypesPage() { return <Layout eyebrow="DEDICATED WORKFLOWS" title="Explore Video Types" intro="Choose the visual style that fits your idea, then build a complete production pack designed for that format." action="Start Creating" actionHref="/create"><section className={`${styles.videoTypeSection} ${compact.styleSection}`}><p className={styles.sectionLead}>Each style uses the same clear, compact card language from the homepage—then opens the existing creation workflow with a matching starting direction.</p><VideoTypeCards hrefFor={(id) => videoTypeCreateHref[id]} /></section><section className={styles.videoTypeCta}><div><p className={styles.eyebrow}>CONNECTED CREATION</p><h2>Ready to Build Your Production Pack?</h2><p>Move into the existing studio to develop characters, define the idea, choose outputs, and review the plan.</p></div><Link className={styles.button} href="/create">Start Creating</Link></section></Layout>; }
export function HowItWorksPage() { const steps = ["Choose a video type", "Build or select characters", "Define the idea, location, object, action, and payoff", "Select the target AI model", "Choose required production outputs", "Generate the production pack", "Review and improve the prompts", "Save or export the final pack"]; return <Layout eyebrow="CONNECTED WORKFLOW" title="From a video idea to a production-ready pack" intro="The studio keeps creative decisions connected so important details can travel through frames, action, sound, quality review, and export."><section className={styles.section}><h2>Eight clear stages</h2><div className={styles.steps}>{steps.map((step, index) => <article className={styles.step} key={step}><span>{String(index + 1).padStart(2, "0")}</span><h3>{step}</h3><p>{index === 0 ? "Select a visual direction before planning the scene." : "Keep the next decision aligned with the production plan."}</p></article>)}</div><Link className={styles.button} href="/create">Start Creating</Link></section></Layout>; }
export function CharacterBuilderPage() { const cards = ["Character Identity", "Visual Appearance", "Personality", "Role", "Clothing and Accessories", "Voice and Vocal Lock", "Movement Style", "Character Consistency", "Hero, Enemy, and Companion roles", "Saving characters to the library"].map((title) => ({ title, copy: `Define ${title.toLowerCase()} once, then carry that detail into selected production outputs.` })); return <Layout eyebrow="CHARACTER-FIRST CREATION" title="Build characters that remain recognizable from frame to frame" intro="Create an original identity with visual locks, behavior, role, movement, and sound guidance. Saved profiles remain available for future productions." action="Build a Character" actionHref="/create?section=characters"><section className={styles.section}><h2>A complete character profile</h2><CardGrid cards={cards} /></section><section className={styles.section}><article className={`${styles.card} ${styles.featured}`}><h3>Example: Biscuit</h3><p>A warm orange squirrel hero with a cream muzzle, a clear silhouette, expressive reactions, and an identity lock that keeps colors, proportions, and role consistent.</p><small>Example only—edit every detail to make your own character.</small></article></section></Layout>; }
export function ProductionPacksPage() { return <Layout eyebrow="ONE CONNECTED PACK" title="Every production detail, organized for the next generation step" intro="Choose a single prompt, selected outputs, or a complete pack. The studio structures the information so the visual plan and sound plan share the same story."><section className={styles.section}><h2>What a complete pack can include</h2><CardGrid cards={productionCards} /></section><section className={styles.section}><h2>Choose the level of output you need</h2><div className={styles.compare}>{["Single Prompt|One focused instruction for a specific creative task.", "Selected Outputs|Only the sections needed for your current tool or workflow.", "Complete Production Pack|A synchronized plan from title and frames through quality review."].map((value) => { const [title, copy] = value.split("|"); return <article className={styles.card} key={title}><h3>{title}</h3><p>{copy}</p></article>; })}</div><Link className={styles.button} href="/create">Generate a Production Pack</Link></section></Layout>; }
export function QualityControlPage() { const cards = ["Character consistency", "Object continuity", "Scene continuity", "Physical action logic", "Camera stability", "Motion clarity", "Hook strength", "Pacing", "Ending payoff", "Duplicate idea prevention", "Contradiction detection", "Model-specific optimization", "Negative prompting", "Fix with AI", "Manual review"].map((title) => ({ title, copy: `Review ${title.toLowerCase()} before sending a production prompt to a video model.` })); return <Layout eyebrow="PROMPT QUALITY CONTROL" title="Review the details that keep a production plan coherent" intro="Quality Control helps identify continuity and clarity risks, then provides transparent findings for creator review. It is guidance—not a guarantee of any model’s final result."><section className={styles.section}><h2>A practical check workflow</h2><CardGrid cards={cards} /><Link className={styles.button} href="/create">Create a Quality-Controlled Pack</Link></section></Layout>; }
export function ModelsPage() { const cards = ["OpenAI video models|Structured creative guidance and prompt refinement.", "Seedance|Direct motion-focused video prompting.", "Kling|Physical motion and camera continuity direction.", "Veo|Cinematic scene description and coherent action.", "OpenArt workflows|Reference-frame and image-to-video workflows.", "General image-generation models|Character and frame concept development.", "Other compatible platforms|Use the universal prompt structure with platform-specific review."].map((value) => { const [title, copy] = value.split("|"); return { title, copy, detail: "Use the model adapter and verify its current controls in that platform." }; }); return <Layout eyebrow="MODEL DIRECTORY" title="Choose a model, then tailor the production guidance" intro="The studio organizes production information for multiple model categories. Exact availability, pricing, duration, and resolution remain determined by the platform you use."><section className={styles.section}><h2>Model categories and practical strengths</h2><CardGrid cards={cards} /><Link className={styles.button} href="/create?section=setup">Choose a Model and Create</Link></section></Layout>; }
export function PricingPage() { const [annual, setAnnual] = useState(false); const plans = [["Starter", "For exploring a repeatable creative workflow."], ["Creator", "For individuals shaping multiple video concepts."], ["Studio", "For teams coordinating a shared production process."], ["Business", "For organizations planning broader creative operations."]]; return <Layout eyebrow="PRICING" title="Plans structured for future commercial release" intro="Plan configuration, pricing, and included usage are not finalized in this preview. These cards provide a clear future-ready structure without inventing commercial terms."><section className={styles.section}><div className={styles.pricingToggle}><button className={!annual ? styles.selected : ""} onClick={() => setAnnual(false)}>Monthly</button><button className={annual ? styles.selected : ""} onClick={() => setAnnual(true)}>Annual</button></div><div className={styles.grid}>{plans.map(([name, copy]) => <article className={`${styles.card} ${name === "Creator" ? styles.featured : ""}`} key={name}><h3>{name}</h3><p>{copy}</p><small>{annual ? "Annual plan values: configurable before release." : "Monthly price: configurable before release."}</small><small>Production pack and credit allocation: configurable.</small><Link href={`/sign-in?plan=${name.toLowerCase()}`}>Choose {name}</Link></article>)}</div></section><section className={styles.section}><h2>Compare plan areas</h2><table className={styles.table}><thead><tr><th>Area</th><th>Starter</th><th>Creator</th><th>Studio</th><th>Business</th></tr></thead><tbody><tr><td>Production workflow</td><td>Configurable</td><td>Configurable</td><td>Configurable</td><td>Configurable</td></tr><tr><td>Team controls</td><td>—</td><td>Configurable</td><td>Configurable</td><td>Configurable</td></tr></tbody></table><h2 style={{ marginTop: 42 }}>Questions about future plans</h2><p className={styles.notice}>Credits, billing, and final plan limits are not connected in this preview. No hidden-fee or usage claims are made here.</p></section></Layout>; }
export function SignInPage() { const [show, setShow] = useState(false); return <Layout eyebrow="ACCOUNT ACCESS" title="Sign in to continue your creative workflow" intro="Account authentication is not connected in this preview. This screen is intentionally a structured interface only and does not submit or store credentials." action="Open the Studio" actionHref="/create"><section className={styles.section}><form className={styles.form} onSubmit={(event) => event.preventDefault()}><label>Email<input type="email" autoComplete="email" placeholder="you@example.com" /></label><label>Password<input type={show ? "text" : "password"} autoComplete="current-password" placeholder="••••••••" /></label><div className={styles.formRow}><label><input type="checkbox" /> Remember me</label><a href="#account-help">Forgot password?</a></div><div className={styles.formRow}><button type="button" onClick={() => setShow((value) => !value)}>{show ? "Hide password" : "Show password"}</button><button type="submit">Sign In</button></div><p id="account-help" className={styles.notice}>Authentication is not yet connected. Create-account and recovery actions are not operational in this preview.</p></form></section></Layout>; }
